export const COFFEE_QOUTES = [
  "But first, coffee.",
  "Life begins after coffee.",
  "Coffee is always a good idea.",
  "A little coffee, a lot of comfort.",
  "Start your day, one cup at a time.",
  "Good days start with great coffee.",
  "Coffee. Pause. Breathe.",
  "One cup closer to a good day.",
  "Brewed for the moment.",
  "Find your perfect blend.",
  "A warm cup for a slow moment.",
  "Every cup tells a story.",
  "Made with care, served with warmth.",
  "Where every sip feels like home.",
  "Take a moment. Enjoy the brew.",
  "Comfort, freshly brewed.",
  "A little warmth in every cup.",
  "Good coffee, better moments.",
  "Let the day unfold, one sip at a time.",
  "Some moments are better with coffee.",
  "Crafted for your everyday ritual.",
  "Thoughtfully brewed. Simply enjoyed.",
  "Your daily ritual, refined.",
  "Great coffee, made intentional.",
  "The art of a better cup.",
  "Small moments. Exceptional coffee.",
  "Brewed with purpose.",
  "Elevate your everyday.",
  "A better brew, a better moment.",
  "Made for those who appreciate the details.",
  "Coffee first, questions later.",
  "Espresso yourself.",
  "Powered by coffee.",
  "Decaf? Not today.",
  "Life is too short for bad coffee.",
  "Coffee is my love language.",
  "Keep calm and drink coffee.",
  "Happiness is a full coffee cup.",
  "Coffee: because adulting is hard.",
  "Less talk, more coffee.",
];
